language: php
sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.4
      env: SYMFONY_VERSION="^4.4"
    - php: 7.4
      env: SYMFONY_VERSION="^5.0"
    - php: 7.4
      env: SYMFONY_VERSION="^5.1"
  allow_failures:
    - php: 7.4
      env: SYMFONY_VERSION="^5.1"

install:
  - composer self-update
  - composer validate
  - composer create-project "symfony/skeleton:${SYMFONY_VERSION}" flex
  - cd flex
  - composer config extra.symfony.allow-contrib true
  - composer require mael/recaptcha-bundle --prefer-dist --no-progress --no-suggest

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)